// Get current time and 24h ago cutoff
const now = new Date();
const cutoff = new Date(now.getTime() - 24 * 60 * 60 * 1000);

const filtered = $input.all().filter(item => {
  const createdAt = item.json.tweet_created_at;
  if (!createdAt) return false;

  // Parse date
  const ts = new Date(createdAt);
  if (isNaN(ts.getTime())) return false;

  // Keep only tweets newer than cutoff
  return ts >= cutoff;
});

return filtered;

//Node 2:

const texts = $input.all().map(i => {
    const t = i.json.tweet_text || '';
    const h = i.json.user_handle || '';
    const u = i.json.tweet_url || '';
    const ts = i.json.tweet_created_at || '';
    return `@${h} | ${ts}\n${t}\n${u}`;
  });
  
  return [{
    json: {
      allTweets: texts.join("\n\n---\n\n"),  // separator
      count: texts.length
    }
  }];

//Node 3:
/**
 * n8n Function/Code node
 * Input: array of items with item.json like:
 *   { row_number, index, message, logprobs, finish_reason }
 * Output: single item with parsed message from the last row.
 */

// ---------- helpers ----------
function safeParseJSON(input) {
    try { return { ok: true, value: JSON.parse(input) }; }
    catch (err) { return { ok: false, error: err }; }
  }
  
  function trimToBalancedJSON(str) {
    let depth = 0;
    let lastGood = -1;
    let inStr = false;
    let esc = false;
    for (let i = 0; i < str.length; i++) {
      const ch = str[i];
  
      // respect strings so braces inside strings don't affect depth
      if (inStr) {
        if (!esc && ch === '\\') { esc = true; continue; }
        if (!esc && ch === '"') inStr = false;
        esc = false;
        continue;
      } else if (ch === '"') {
        inStr = true;
        continue;
      }
  
      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) lastGood = i;
        if (depth < 0) break;
      }
    }
    return lastGood >= 0 ? str.slice(0, lastGood + 1) : str;
  }
  
  function extractMessageFromRow(row) {
    const notes = [];
    const raw = row.message ?? '';
  
    // parse outer message
    let outer = safeParseJSON(raw);
    if (!outer.ok) {
      const trimmed = trimToBalancedJSON(raw);
      if (trimmed !== raw) {
        notes.push('Trimmed outer message to balanced JSON.');
        outer = safeParseJSON(trimmed);
      }
    }
    if (!outer.ok || typeof outer.value !== 'object') {
      return {
        row_number: row.row_number ?? null,
        role: null,
        content: null,
        raw,
        notes: ['Failed to parse outer message JSON.'].concat(notes),
      };
    }
  
    const role = outer.value.role ?? null;
    let content = outer.value.content ?? null;
  
    // inner content may be JSON-as-string
    if (typeof content === 'string') {
      let inner = safeParseJSON(content);
      if (!inner.ok) {
        const trimmedInner = trimToBalancedJSON(content);
        if (trimmedInner !== content) {
          notes.push('Trimmed inner content to balanced JSON.');
          inner = safeParseJSON(trimmedInner);
        }
      }
      if (inner.ok) content = inner.value;
      else notes.push('Inner content could not be parsed; leaving as string.');
    }
  
    return {
      row_number: row.row_number ?? null,
      role,
      content,
      raw,
      notes,
    };
  }
  
  // ---------- main ----------
  const rows = items.map(i => i.json);
  
  // Choose the last row by highest row_number if available, else last element
  let lastRow;
  const haveRowNums = rows.every(r => typeof r.row_number === 'number');
  if (haveRowNums && rows.length) {
    lastRow = rows.reduce((a, b) => (a.row_number > b.row_number ? a : b));
  } else {
    lastRow = rows[rows.length - 1];
  }
  
  const parsed = extractMessageFromRow(lastRow);
  
  // Return a single item
  return [
    {
      json: parsed
    }
  ];

 // Node 4:
 /**
 * n8n Code node (v2) — JavaScript
 * Input: items[].json with either:
 *  - { row_number, content: {...} }  (preferred), or
 *  - { row_number, message: "<json string>" } (fallback)
 * Output: [{ json: { subject, html, text } }]
 */

// ---------- helpers ----------
function esc(s) {
    return String(s ?? "")
      .replace(/&/g, "&amp;").replace(/</g, "&lt;")
      .replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function has(arr) { return Array.isArray(arr) && arr.length > 0; }
  
  function buildEmailHTML(content, options = {}) {
    const {
      title = "Daily Market Brief",
      date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }),
      brandColor = "#0d1117",
      accentColor = "#2f81f7",
      footerNote = "Generated by your n8n automation",
    } = options;
  
    const sectionHeading = (txt) => `
      <tr>
        <td style="padding:18px 20px 8px 20px;">
          <h2 style="margin:0;font-size:18px;line-height:1.3;font-weight:700;color:${brandColor};">${esc(txt)}</h2>
        </td>
      </tr>`;
  
    const badge = (label) => `
      <span style="display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;">
        ${esc(label)}
      </span>`;
  
    const renderSummary = () => (!content?.summary ? "" : `
      ${sectionHeading("Summary")}
      <tr>
        <td style="padding:8px 20px 16px 20px;color:#24292f;font-size:14px;line-height:1.6;">
          ${esc(content.summary)}
        </td>
      </tr>`);
  
    const renderInsights = () => (!has(content?.insights) ? "" : `
      ${sectionHeading("Insights")}
      <tr>
        <td style="padding:6px 12px 2px 12px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
            <tbody>
              ${content.insights.map(it => `
                <tr>
                  <td style="padding:10px;border-bottom:1px solid #eaeef2;">
                    <div style="font-size:14px;">
                      <strong style="background:${accentColor};color:#fff;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;">
                        ${esc(it.ticker || "")}
                      </strong>
                      <span style="color:#24292f;">${esc(it.bullet || "")}</span>
                    </div>
                    <div style="margin-top:6px;font-size:12px;color:#57606a;">
                      ${it.horizon ? badge(`Horizon: ${it.horizon}`) : ""}
                      ${it.conviction ? badge(`Conviction: ${it.conviction}`) : ""}
                    </div>
                    ${it.recommendation ? `
                      <div style="margin-top:8px;font-size:13px;color:#24292f;">
                        <em>${esc(it.recommendation)}</em>
                      </div>` : ""}
                  </td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </td>
      </tr>`);
  
    const renderWatchlist = () => (!has(content?.watchlist) ? "" : `
      ${sectionHeading("Watchlist")}
      <tr>
        <td style="padding:6px 12px 2px 12px;">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
            <tbody>
              ${content.watchlist.map(w => `
                <tr>
                  <td style="padding:10px;border-bottom:1px solid #eaeef2;">
                    <div style="font-size:14px;">
                      <strong style="background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;">
                        ${esc(w.ticker || "")}
                      </strong>
                      <span style="color:#24292f;">${esc(w.why || "")}</span>
                    </div>
                    <div style="margin-top:6px;font-size:12px;color:#57606a;">
                      ${w.horizon ? badge(`Horizon: ${w.horizon}`) : ""}
                    </div>
                    ${w.recommendation ? `
                      <div style="margin-top:8px;font-size:13px;color:#24292f;">
                        <em>${esc(w.recommendation)}</em>
                      </div>` : ""}
                  </td>
                </tr>
              `).join("")}
            </tbody>
          </table>
        </td>
      </tr>`);
  
    const renderSources = () => (!has(content?.sources) ? "" : `
      ${sectionHeading("Sources")}
      <tr>
        <td style="padding:6px 20px 16px 20px;">
          <ul style="margin:0;padding-left:18px;color:#24292f;font-size:13px;line-height:1.6;">
            ${content.sources.map(s => `
              <li style="margin-bottom:6px;">
                ${s.note ? `<span>${esc(s.note)} — </span>` : ""}
                <a href="${esc(s.url || "#")}" style="color:${accentColor};text-decoration:none;">${esc(s.url)}</a>
              </li>
            `).join("")}
          </ul>
        </td>
      </tr>`);
  
    const html = `
    <!doctype html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>${esc(title)}</title>
    </head>
    <body style="margin:0;padding:0;background:#f6f8fa;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f6f8fa;">
        <tr>
          <td style="padding:20px 12px;">
            <table role="presentation" cellpadding="0" cellspacing="0" border="0" align="center" width="100%" style="max-width:600px;background:#ffffff;border:1px solid #eaeef2;border-radius:10px;overflow:hidden;">
              <tr>
                <td style="background:${brandColor};padding:18px 20px;">
                  <h1 style="margin:0;font-size:20px;line-height:1.2;color:#ffffff;">${esc(title)}</h1>
                  <div style="margin-top:4px;font-size:12px;color:#c9d1d9;">${esc(date)}</div>
                </td>
              </tr>
  
              ${renderSummary()}
              ${renderInsights()}
              ${renderWatchlist()}
              ${renderSources()}
  
              <tr>
                <td style="padding:16px 20px;background:#fafbfc;border-top:1px solid #eaeef2;color:#57606a;font-size:12px;">
                  ${esc(footerNote)}
                </td>
              </tr>
            </table>
  
            <div style="max-width:600px;margin:10px auto 0 auto;font-size:11px;color:#6e7781;text-align:center;">
              You’re receiving this because you subscribed to daily market updates.
            </div>
          </td>
        </tr>
      </table>
    </body>
    </html>`.trim();
  
    const text = [
      `${title} — ${date}`,
      "",
      content.summary ? `Summary:\n${content.summary}\n` : "",
      has(content.insights) ? `Insights:\n${content.insights.map(i =>
        `- ${i.ticker}: ${i.bullet} [Horizon: ${i.horizon || "-"}, Conviction: ${i.conviction || "-"}]\n  Recommendation: ${i.recommendation || "-"}`
      ).join("\n")}\n` : "",
      has(content.watchlist) ? `Watchlist:\n${content.watchlist.map(w =>
        `- ${w.ticker}: ${w.why} [Horizon: ${w.horizon || "-"}]\n  Recommendation: ${w.recommendation || "-"}`
      ).join("\n")}\n` : "",
      has(content.sources) ? `Sources:\n${content.sources.map(s => `- ${s.note || ""} ${s.url || ""}`).join("\n")}` : "",
    ].join("\n");
  
    const subject = `Market Brief — ${date}`;
    return { subject, html, text };
  }
  
  // ---------- MAIN ----------
  if (!Array.isArray(items) || items.length === 0) {
    return [{ json: { error: "No input items" } }];
  }
  
  // pick last by row_number (fallback: last element)
  const rows = items.map(i => i.json || {});
  const haveRowNums = rows.every(r => typeof r.row_number === 'number');
  const lastRow = haveRowNums
    ? rows.reduce((a, b) => (a.row_number > b.row_number ? a : b))
    : rows[rows.length - 1];
  
  // prefer parsed content; fallback to raw/message if needed
  let content = lastRow.content;
  if (!content && typeof lastRow.message === 'string') {
    try {
      const outer = JSON.parse(lastRow.message);
      content = typeof outer?.content === 'string' ? JSON.parse(outer.content) : outer.content;
    } catch (e) {
      return [{ json: { error: "Failed to parse content from message", details: String(e) } }];
    }
  }
  
  if (!content || typeof content !== 'object') {
    return [{ json: { error: "Missing or invalid content object on last row" } }];
  }
  
  const { subject, html, text } = buildEmailHTML(content, {
    title: "Aarush's Daily Market Brief",
    brandColor: "#111827",
    accentColor: "#2563eb",
    footerNote: "Built with n8n + OpenAI",
  });
  
  // Extract date in YYYY-MM-DD format
  const dateObj = new Date();
  const dateISO = dateObj.toISOString().split('T')[0]; // "2025-10-12"
  
  // ✅ Return exactly an array of items with all required fields for the website
  return [{
    json: {
      id: dateISO,           // for hash routing (#2025-10-12)
      date: dateISO,         // for sorting and display
      subject,               // "Market Brief — October 12, 2025"
      json: content,         // structured content (summary, insights, watchlist, sources)
      html,                  // keep for email
      text                   // keep for email plaintext
    }
  }];
  


  //node 4 most recent output:
//   [
//     {
//       "id": "2025-10-12",
//       "date": "2025-10-12",
//       "subject": "Market Brief — October 12, 2025",
//       "json": {
//         "summary": "Today's tweets highlight significant themes in rare earth elements, AI infrastructure, and market dynamics. There is a focus on the strategic importance of rare earth elements, particularly in the context of U.S.-China relations, with $MP being a notable company in this sector. The AI infrastructure landscape is evolving, with companies like $NBIS playing a crucial role in providing scalable compute solutions. Market sentiment is mixed, with discussions on potential pullbacks and the importance of long-term investment strategies. Additionally, $AMZN is highlighted for its robust growth across various sectors, including AWS and AI integration.",
//         "insights": [
//           {
//             "ticker": "MP",
//             "bullet": "Potential beneficiary of U.S. efforts to build a domestic rare earth supply chain.",
//             "horizon": "long-term",
//             "conviction": "medium",
//             "recommendation": "Consider investing due to strategic importance in rare earth supply."
//           },
//           {
//             "ticker": "NBIS",
//             "bullet": "Critical role in AI infrastructure by providing scalable compute solutions.",
//             "horizon": "long-term",
//             "conviction": "high",
//             "recommendation": "Invest for exposure to AI infrastructure growth."
//           },
//           {
//             "ticker": "AMZN",
//             "bullet": "Strong growth in AWS, ad business, and AI integration.",
//             "horizon": "long-term",
//             "conviction": "high",
//             "recommendation": "Invest for long-term growth across multiple sectors."
//           },
//           {
//             "ticker": "ASTS",
//             "bullet": "Secured significant deals with global carriers, enhancing its market position.",
//             "horizon": "long-term",
//             "conviction": "medium",
//             "recommendation": "Consider investing as it expands its global telecom reach."
//           }
//         ],
//         "watchlist": [
//           {
//             "ticker": "GXO",
//             "why": "Potential play in robotics and automation.",
//             "horizon": "short-term",
//             "recommendation": "Monitor for entry opportunities."
//           },
//           {
//             "ticker": "RDW",
//             "why": "Undervalued space sector opportunity.",
//             "horizon": "short-term",
//             "recommendation": "Monitor for potential undervaluation."
//           },
//           {
//             "ticker": "JOBY",
//             "why": "Leader in the eVTOL sector.",
//             "horizon": "long-term",
//             "recommendation": "Monitor for technological advancements."
//           },
//           {
//             "ticker": "HLX",
//             "why": "Involved in robotics and offshore energy.",
//             "horizon": "short-term",
//             "recommendation": "Monitor for sector developments."
//           },
//           {
//             "ticker": "VNET",
//             "why": "Deep value in China data-center operations.",
//             "horizon": "long-term",
//             "recommendation": "Monitor for valuation improvements."
//           }
//         ],
//         "sources": [
//           {
//             "url": "https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.561Z",
//             "note": "Rare Earth Elements write-up"
//           },
//           {
//             "url": "https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.562Z",
//             "note": "AI infrastructure discussion"
//           },
//           {
//             "url": "https://twitter.com/StockSavvyShay/status/2025-10-12T13:55:50.296Z",
//             "note": "Amazon growth analysis"
//           },
//           {
//             "url": "https://twitter.com/spacanpanman/status/2025-10-12T13:56:09.474Z",
//             "note": "AST SpaceMobile deal announcement"
//           }
//         ]
//       },
//       "html": "<!doctype html>\n    <html>\n    <head>\n      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n      <title>Aarush&#39;s Daily Market Brief</title>\n    </head>\n    <body style=\"margin:0;padding:0;background:#f6f8fa;\">\n      <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" style=\"background:#f6f8fa;\">\n        <tr>\n          <td style=\"padding:20px 12px;\">\n            <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" width=\"100%\" style=\"max-width:600px;background:#ffffff;border:1px solid #eaeef2;border-radius:10px;overflow:hidden;\">\n              <tr>\n                <td style=\"background:#111827;padding:18px 20px;\">\n                  <h1 style=\"margin:0;font-size:20px;line-height:1.2;color:#ffffff;\">Aarush&#39;s Daily Market Brief</h1>\n                  <div style=\"margin-top:4px;font-size:12px;color:#c9d1d9;\">October 12, 2025</div>\n                </td>\n              </tr>\n  \n              \n      \n      <tr>\n        <td style=\"padding:18px 20px 8px 20px;\">\n          <h2 style=\"margin:0;font-size:18px;line-height:1.3;font-weight:700;color:#111827;\">Summary</h2>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"padding:8px 20px 16px 20px;color:#24292f;font-size:14px;line-height:1.6;\">\n          Today&#39;s tweets highlight significant themes in rare earth elements, AI infrastructure, and market dynamics. There is a focus on the strategic importance of rare earth elements, particularly in the context of U.S.-China relations, with $MP being a notable company in this sector. The AI infrastructure landscape is evolving, with companies like $NBIS playing a crucial role in providing scalable compute solutions. Market sentiment is mixed, with discussions on potential pullbacks and the importance of long-term investment strategies. Additionally, $AMZN is highlighted for its robust growth across various sectors, including AWS and AI integration.\n        </td>\n      </tr>\n              \n      \n      <tr>\n        <td style=\"padding:18px 20px 8px 20px;\">\n          <h2 style=\"margin:0;font-size:18px;line-height:1.3;font-weight:700;color:#111827;\">Insights</h2>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"padding:6px 12px 2px 12px;\">\n          <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse;\">\n            <tbody>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#2563eb;color:#fff;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        MP\n                      </strong>\n                      <span style=\"color:#24292f;\">Potential beneficiary of U.S. efforts to build a domestic rare earth supply chain.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Conviction: medium\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Consider investing due to strategic importance in rare earth supply.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#2563eb;color:#fff;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        NBIS\n                      </strong>\n                      <span style=\"color:#24292f;\">Critical role in AI infrastructure by providing scalable compute solutions.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Conviction: high\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Invest for exposure to AI infrastructure growth.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#2563eb;color:#fff;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        AMZN\n                      </strong>\n                      <span style=\"color:#24292f;\">Strong growth in AWS, ad business, and AI integration.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Conviction: high\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Invest for long-term growth across multiple sectors.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#2563eb;color:#fff;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        ASTS\n                      </strong>\n                      <span style=\"color:#24292f;\">Secured significant deals with global carriers, enhancing its market position.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Conviction: medium\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Consider investing as it expands its global telecom reach.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n            </tbody>\n          </table>\n        </td>\n      </tr>\n              \n      \n      <tr>\n        <td style=\"padding:18px 20px 8px 20px;\">\n          <h2 style=\"margin:0;font-size:18px;line-height:1.3;font-weight:700;color:#111827;\">Watchlist</h2>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"padding:6px 12px 2px 12px;\">\n          <table role=\"presentation\" width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse;\">\n            <tbody>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        GXO\n                      </strong>\n                      <span style=\"color:#24292f;\">Potential play in robotics and automation.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: short-term\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Monitor for entry opportunities.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        RDW\n                      </strong>\n                      <span style=\"color:#24292f;\">Undervalued space sector opportunity.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: short-term\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Monitor for potential undervaluation.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        JOBY\n                      </strong>\n                      <span style=\"color:#24292f;\">Leader in the eVTOL sector.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Monitor for technological advancements.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        HLX\n                      </strong>\n                      <span style=\"color:#24292f;\">Involved in robotics and offshore energy.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: short-term\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Monitor for sector developments.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n                <tr>\n                  <td style=\"padding:10px;border-bottom:1px solid #eaeef2;\">\n                    <div style=\"font-size:14px;\">\n                      <strong style=\"background:#eaeef2;color:#24292f;border-radius:6px;padding:2px 6px;margin-right:8px;display:inline-block;\">\n                        VNET\n                      </strong>\n                      <span style=\"color:#24292f;\">Deep value in China data-center operations.</span>\n                    </div>\n                    <div style=\"margin-top:6px;font-size:12px;color:#57606a;\">\n                      \n      <span style=\"display:inline-block;padding:3px 8px;border:1px solid #d0d7de;border-radius:999px;font-size:12px;line-height:1.2;margin-right:6px;\">\n        Horizon: long-term\n      </span>\n                    </div>\n                    \n                      <div style=\"margin-top:8px;font-size:13px;color:#24292f;\">\n                        <em>Monitor for valuation improvements.</em>\n                      </div>\n                  </td>\n                </tr>\n              \n            </tbody>\n          </table>\n        </td>\n      </tr>\n              \n      \n      <tr>\n        <td style=\"padding:18px 20px 8px 20px;\">\n          <h2 style=\"margin:0;font-size:18px;line-height:1.3;font-weight:700;color:#111827;\">Sources</h2>\n        </td>\n      </tr>\n      <tr>\n        <td style=\"padding:6px 20px 16px 20px;\">\n          <ul style=\"margin:0;padding-left:18px;color:#24292f;font-size:13px;line-height:1.6;\">\n            \n              <li style=\"margin-bottom:6px;\">\n                <span>Rare Earth Elements write-up — </span>\n                <a href=\"https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.561Z\" style=\"color:#2563eb;text-decoration:none;\">https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.561Z</a>\n              </li>\n            \n              <li style=\"margin-bottom:6px;\">\n                <span>AI infrastructure discussion — </span>\n                <a href=\"https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.562Z\" style=\"color:#2563eb;text-decoration:none;\">https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.562Z</a>\n              </li>\n            \n              <li style=\"margin-bottom:6px;\">\n                <span>Amazon growth analysis — </span>\n                <a href=\"https://twitter.com/StockSavvyShay/status/2025-10-12T13:55:50.296Z\" style=\"color:#2563eb;text-decoration:none;\">https://twitter.com/StockSavvyShay/status/2025-10-12T13:55:50.296Z</a>\n              </li>\n            \n              <li style=\"margin-bottom:6px;\">\n                <span>AST SpaceMobile deal announcement — </span>\n                <a href=\"https://twitter.com/spacanpanman/status/2025-10-12T13:56:09.474Z\" style=\"color:#2563eb;text-decoration:none;\">https://twitter.com/spacanpanman/status/2025-10-12T13:56:09.474Z</a>\n              </li>\n            \n          </ul>\n        </td>\n      </tr>\n  \n              <tr>\n                <td style=\"padding:16px 20px;background:#fafbfc;border-top:1px solid #eaeef2;color:#57606a;font-size:12px;\">\n                  Built with n8n + OpenAI\n                </td>\n              </tr>\n            </table>\n  \n            <div style=\"max-width:600px;margin:10px auto 0 auto;font-size:11px;color:#6e7781;text-align:center;\">\n              You’re receiving this because you subscribed to daily market updates.\n            </div>\n          </td>\n        </tr>\n      </table>\n    </body>\n    </html>",
//       "text": "Aarush's Daily Market Brief — October 12, 2025\n\nSummary:\nToday's tweets highlight significant themes in rare earth elements, AI infrastructure, and market dynamics. There is a focus on the strategic importance of rare earth elements, particularly in the context of U.S.-China relations, with $MP being a notable company in this sector. The AI infrastructure landscape is evolving, with companies like $NBIS playing a crucial role in providing scalable compute solutions. Market sentiment is mixed, with discussions on potential pullbacks and the importance of long-term investment strategies. Additionally, $AMZN is highlighted for its robust growth across various sectors, including AWS and AI integration.\n\nInsights:\n- MP: Potential beneficiary of U.S. efforts to build a domestic rare earth supply chain. [Horizon: long-term, Conviction: medium]\n  Recommendation: Consider investing due to strategic importance in rare earth supply.\n- NBIS: Critical role in AI infrastructure by providing scalable compute solutions. [Horizon: long-term, Conviction: high]\n  Recommendation: Invest for exposure to AI infrastructure growth.\n- AMZN: Strong growth in AWS, ad business, and AI integration. [Horizon: long-term, Conviction: high]\n  Recommendation: Invest for long-term growth across multiple sectors.\n- ASTS: Secured significant deals with global carriers, enhancing its market position. [Horizon: long-term, Conviction: medium]\n  Recommendation: Consider investing as it expands its global telecom reach.\n\nWatchlist:\n- GXO: Potential play in robotics and automation. [Horizon: short-term]\n  Recommendation: Monitor for entry opportunities.\n- RDW: Undervalued space sector opportunity. [Horizon: short-term]\n  Recommendation: Monitor for potential undervaluation.\n- JOBY: Leader in the eVTOL sector. [Horizon: long-term]\n  Recommendation: Monitor for technological advancements.\n- HLX: Involved in robotics and offshore energy. [Horizon: short-term]\n  Recommendation: Monitor for sector developments.\n- VNET: Deep value in China data-center operations. [Horizon: long-term]\n  Recommendation: Monitor for valuation improvements.\n\nSources:\n- Rare Earth Elements write-up https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.561Z\n- AI infrastructure discussion https://twitter.com/mvcinvesting/status/2025-10-12T13:55:16.562Z\n- Amazon growth analysis https://twitter.com/StockSavvyShay/status/2025-10-12T13:55:50.296Z\n- AST SpaceMobile deal announcement https://twitter.com/spacanpanman/status/2025-10-12T13:56:09.474Z"
//     }
//   ]